Repository ros2/launch, pull requests merged in 2018-07, with the labels that each got.

#96 Fix exception when launch process with environment variables
  launch/launch/actions/execute_process.py
  launch/test/launch/env_echo.py
  launch/test/launch/test_execute_process.py
Labels: bug, in review

#100 Ignore warning for builtins A003
  launch/launch/launch_context.py
Labels: in review

#99 Avoid reentrancy of sigterm and sigquit signal handlers
  launch/launch/launch_service.py
Labels: in review

#82 move suppression of KeyboardInterrupt
  launch/launch/launch_service.py
  launch/launch/utilities/signal_management.py
Labels: enhancement, in review

#118 Fast-forward bouncy to catchup with master for patch 1 release
  launch/CHANGELOG.rst
  launch/launch/actions/execute_process.py
  launch/launch/launch_context.py
  launch/launch/launch_service.py
  launch/launch/utilities/signal_management.py
  launch/package.xml
  launch/test/launch/env_echo.py
  launch/test/launch/test_execute_process.py
  launch_ros/CHANGELOG.rst
  launch_ros/package.xml
  launch_testing/CHANGELOG.rst
  launch_testing/package.xml
  ros2launch/CHANGELOG.rst
  ros2launch/package.xml
Labels: in review

#119 avoid race in emitting event by using loop.call_soon_threadsafe()
  launch_ros/examples/lifecycle_pub_sub_launch.py
  launch_ros/launch_ros/actions/lifecycle_node.py
Labels: bug, in review

#120 add IncludeLaunchDescription action
  launch/launch/__init__.py
  launch/launch/actions/__init__.py
  launch/launch/actions/include_launch_description.py
  launch/launch/launch_description_source.py
  launch/test/launch/actions/test_include_launch_description.py
  launch/test/launch/test_action.py
Labels: in review

#121 implement Action conditions
  launch/doc/source/architecture.rst
  launch/launch/__init__.py
  launch/launch/action.py
  launch/launch/actions/emit_event.py
  launch/launch/actions/execute_process.py
  launch/launch/actions/log_info.py
  launch/launch/actions/opaque_function.py
  launch/launch/actions/register_event_handler.py
  launch/launch/actions/set_launch_configuration.py
  launch/launch/actions/timer_action.py
  launch/launch/condition.py
  launch/launch/conditions/__init__.py
  launch/launch/conditions/evaluate_condition_expression_impl.py
  launch/launch/conditions/if_condition.py
  launch/launch/conditions/invalid_condition_expression_error.py
  launch/launch/conditions/unless_condition.py
  launch/test/launch/conditions/test_evaluate_condition_expression.py
  launch/test/launch/conditions/test_if_condition.py
  launch/test/launch/conditions/test_unless_condition.py
  launch/test/launch/test_action.py
  launch/test/launch/test_condition.py
Labels: in review
