Repository ros2/launch, pull requests merged in 2018-10, with the labels that each got.

#142 Add tests for class_tools_impl and fix is_a_subclass()
  launch/launch/utilities/class_tools_impl.py
  launch/test/launch/utilities/test_class_tools.py
Labels: in review

#150 always use shell to avoid inconsistency of time being a shell command or executable
  launch/examples/launch_counters.py
Labels: bug, in review

#151 Fix lint warnings from invalid escape sequences
  launch_testing/test/test_matching.py
Labels: in progress
