Repository ros2/launch, pull requests merged in 2018-06, with the labels that each got.

#73 move launch files into launch.legacy namespace
  launch/launch/__init__.py
  launch/launch/legacy/__init__.py
  launch/launch/legacy/arguments.py
  launch/launch/legacy/exit_handler.py
  launch/launch/legacy/launch.py
  launch/launch/legacy/launcher.py
  launch/launch/legacy/loader.py
  launch/launch/legacy/main.py
  launch/launch/legacy/output_handler.py
  launch/launch/legacy/protocol.py
  launch/launch/legacy/task.py
  launch/test/legacy/counter.py
  launch/test/legacy/launch_counter.py
  launch/test/legacy/launch_multiple_counters.py
  launch/test/legacy/test_interrupt_default_launcher.py
  launch/test/legacy/test_launch_args.py
  launch/test/legacy/test_launch_with_coroutine.py
  launch/test/legacy/test_multiple_launch.py
  launch/test/legacy/test_non_primary_return_code.py
  launch_testing/launch_testing/__init__.py
  launch_testing/test/test_env_passing.py
  launch_testing/test/test_matching.py
Labels: in review

#75 ROS specific launch
  launch_ros/examples/lifecycle_pub_sub_launch.py
  launch_ros/examples/pub_sub_launch.py
  launch_ros/launch_ros/__init__.py
  launch_ros/launch_ros/actions/__init__.py
  launch_ros/launch_ros/actions/lifecycle_node.py
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/default_launch_description.py
  launch_ros/launch_ros/event_handlers/__init__.py
  launch_ros/launch_ros/event_handlers/on_state_transition.py
  launch_ros/launch_ros/events/__init__.py
  launch_ros/launch_ros/events/lifecycle/__init__.py
  launch_ros/launch_ros/events/lifecycle/change_state.py
  launch_ros/launch_ros/events/lifecycle/lifecycle_node_matchers.py
  launch_ros/launch_ros/events/lifecycle/state_transition.py
  launch_ros/launch_ros/substitutions/__init__.py
  launch_ros/launch_ros/substitutions/executable_in_package.py
  launch_ros/package.xml
  launch_ros/setup.py
  launch_ros/test/test_copyright.py
  launch_ros/test/test_flake8.py
  launch_ros/test/test_pep257.py
Labels: enhancement, in review

#77 Small fixups from launch PR
  launch/launch/utilities/signal_management.py
  launch/test/test_copyright.py
  launch_ros/package.xml
  launch_ros/test/test_copyright.py
  launch_ros/test/test_flake8.py
  launch_ros/test/test_pep257.py
Labels: in review

#76 ros2launch CLI
  launch/launch/launch_service.py
  launch_ros/launch_ros/default_launch_description.py
  ros2launch/examples/example.launch.py
  ros2launch/package.xml
  ros2launch/ros2launch/__init__.py
  ros2launch/ros2launch/api/__init__.py
  ros2launch/ros2launch/api/api.py
  ros2launch/ros2launch/command/__init__.py
  ros2launch/ros2launch/command/launch.py
  ros2launch/setup.py
  ros2launch/test/test_copyright.py
  ros2launch/test/test_flake8.py
  ros2launch/test/test_pep257.py
Labels: enhancement, in review

#81 Use variable typing in comments to support python 3.5
  launch/launch/actions/execute_process.py
  launch/launch/actions/opaque_function.py
  launch/launch/actions/timer_action.py
  launch/launch/event_handler.py
  launch/launch/event_handlers/on_process_exit.py
  launch/launch/event_handlers/on_process_io.py
  launch/launch/events/process/process_exited.py
  launch/launch/events/process/process_stdout.py
  launch/launch/events/process/running_process_event.py
  launch/launch/events/process/shutdown_process.py
  launch/launch/launch_context.py
  launch/launch/launch_introspector.py
  launch/launch/launch_service.py
  launch/launch/substitutions/launch_configuration.py
  launch/launch/substitutions/text_substitution.py
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/default_launch_description.py
  launch_ros/launch_ros/event_handlers/on_state_transition.py
  launch_ros/launch_ros/events/lifecycle/change_state.py
  launch_ros/launch_ros/events/lifecycle/state_transition.py
Labels: in review

#85 keep track of, and then close at exit, all asyncio loops
  launch/launch/launch_service.py
Labels: in review

#87 Windows Fixes
  launch/examples/launch_counters.py
  launch/launch/actions/execute_process.py
  launch/launch/events/process/signal_process.py
  launch/launch/launch_service.py
  launch/test/launch/test_launch_service.py
  launch_ros/examples/lifecycle_pub_sub_launch.py
  launch_ros/examples/pub_sub_launch.py
Labels: bug, in review

#93 improve error handling in ros2 launch command line tool
  ros2launch/ros2launch/api/__init__.py
  ros2launch/ros2launch/command/launch.py
Labels: enhancement, in review

#94 avoid SIGINT on Windows
  launch/launch/actions/execute_process.py
Labels: bug, in review
