Repository ros2/launch, pull requests merged in 2018-08, with the labels that each got.

#122 add way to include other Python launch files
  launch/launch/actions/include_launch_description.py
  launch/launch/launch_description_source.py
  launch/launch/launch_description_sources/__init__.py
  launch/launch/launch_description_sources/python_launch_description_source.py
  launch/launch/launch_description_sources/python_launch_file_utilities.py
  launch/launch/launch_service.py
  launch/launch/substitutions/__init__.py
  launch/launch/substitutions/this_launch_file_dir.py
  launch/test/launch/actions/test_include_launch_description.py
  launch/test/launch/launch_description_source/loadable_python_module.py
  launch/test/launch/launch_description_source/simple.launch.py
  launch/test/launch/launch_description_source/test_python_launch_description_source.py
  launch/test/launch/launch_description_source/test_python_launch_file_utilities.py
  launch/test/launch/substitutions/test_this_launch_file_dir.py
  launch/test/launch/test_launch_description_entity.py
  launch/test/launch/test_launch_description_source.py
  ros2launch/examples/includes_example.launch.py
  ros2launch/ros2launch/api/api.py
Labels: in review

#124 destroy node on shutdown to avoid hang
  launch_ros/launch_ros/default_launch_description.py
Labels: bug, in review

#128 add a new pair of actions for pushing and popping launch configurations
  launch/launch/actions/__init__.py
  launch/launch/actions/pop_launch_configurations.py
  launch/launch/actions/push_launch_configurations.py
  launch/test/launch/actions/test_push_and_pop_launch_configurations.py
Labels: in review

#129 add optional name argument to ExecuteProcess
  launch/launch/actions/execute_process.py
Labels: enhancement, in review

#130 move launch_testing into launch_testing.legacy namespace
  launch_testing/launch_testing/__init__.py
  launch_testing/launch_testing/legacy/__init__.py
Labels: enhancement, in review

#131 add class to provide some limited testing options
  launch_testing/launch_testing/__init__.py
Labels: enhancement, in review

#132 Fix linter errors from #131.
  launch_testing/launch_testing/__init__.py
Labels: in review

#133 add GroupAction for conditionally including other actions and scoping
  launch/launch/actions/__init__.py
  launch/launch/actions/group_action.py
  launch/test/launch/actions/test_group_action.py
Labels: enhancement, in review

#134 add UnsetLaunchConfiguration action and tests
  launch/launch/actions/__init__.py
  launch/launch/actions/unset_launch_configuration.py
  launch/test/launch/actions/test_set_and_unset_launch_configuration.py
Labels: enhancement, in review
