Repository ros2/launch, pull requests merged in 2019-08, with the labels that each got.

#294 Correct launch service sigterm handling
  launch/launch/launch_service.py
Labels: in review

#297 Avoid closing event loop in atexit hook on windows
  launch/launch/launch_service.py
Labels: in review

#296 Fix launch_testing output filtering
  launch_testing/launch_testing/tools/output.py
  launch_testing/test/launch_testing/test_tools.py
Labels: bug

#210 Add async run method to LaunchService
  launch/launch/launch_service.py
  launch/launch/utilities/signal_management.py
  launch/test/launch/test_launch_service.py
Labels: in review

#307 Fix test_expose_decorators failures
  launch/launch/frontend/expose.py
  launch/test/launch/frontend/test_expose_decorators.py
Labels: in review

#308 Support LaunchService injection into pre-shutdown tests.
  launch/launch/actions/execute_process.py
  launch_testing/example_processes/terminating_proc
  launch_testing/examples/README.md
  launch_testing/examples/example_test_context.test.py
  launch_testing/examples/terminating_proc.test.py
  launch_testing/launch_testing/test_runner.py
  launch_testing/launch_testing/tools/__init__.py
  launch_testing/launch_testing/tools/launchers.py
Labels: in review

#310 Fix launch argument listing/checking issues
  launch/launch/action.py
  launch/launch/actions/group_action.py
  launch/launch/actions/include_launch_description.py
Labels: bug, in review

#315 Improve error message when a failing to include launch file
  launch/launch/invalid_launch_file_error.py
  launch/launch/launch_description_sources/any_launch_file_utilities.py
Labels: in review

#319 fix expectation for test on Windows
  launch/test/launch/actions/test_emulate_tty.py
Labels: in review

#284 Make IncludeLaunchDescription force launch_arguments iterable on construction
  launch/launch/actions/include_launch_description.py
Labels: in review

#323 install package marker and manifest
  launch/resource/launch
  launch/setup.py
Labels: bug, in review
