Repository ros2/launch, pull requests merged in 2019-06, with the labels that each got.

#255 Line buffering of logger output
  launch/launch/actions/execute_process.py
Labels: in review

#259 Fix build_cop #214
  launch/launch/actions/execute_process.py
Labels: bug, in review

#256 Remove launch_testing dependency on ros domain ID
  launch_testing/README.md
  launch_testing/launch_testing/domain_coordinator.py
  launch_testing/launch_testing/launch_test.py
  launch_testing/test/launch_testing/test_domain_coordinator.py
  launch_testing/test/launch_testing/test_resolve_process.py
Labels: in review

#229 Fix proc lookup for processes with multiple command-line arguments
  launch_testing/example_processes/good_proc
  launch_testing/launch_testing/util/proc_lookup.py
  launch_testing/test/launch_testing/test_resolve_process.py
Labels: in review

#266 Add PathJoinSubstitution
  launch/launch/substitutions/__init__.py
  launch/launch/substitutions/path_join_substitution.py
  launch/test/launch/substitutions/test_path_join_substitution.py
Labels: enhancement, in review
