Repository ros2/launch, pull requests merged in 2019-05, with the labels that each got.

#228 Make launchtest junit XML match pytest XML more closely
  launch_testing/launch_testing/junitxml.py
  launch_testing/launch_testing/launch_test.py
  launch_testing/launch_testing/loader.py
  launch_testing/launch_testing/test_result.py
  launch_testing/launch_testing/test_runner.py
  launch_testing/test/launch_testing/test_launch_test_runner_validation.py
  launch_testing/test/launch_testing/test_runner_results.py
  launch_testing/test/launch_testing/test_xml_output.py
  launch_testing_ament_cmake/cmake/add_launch_test.cmake
Labels: in review

#231 Sync missing parametrization commits
  launch_testing/launch_testing/loader.py
  launch_testing/launch_testing/test_runner.py
  launch_testing/test/launch_testing/test_launch_test_runner_validation.py
Labels: in review

#233 Add support for custom launch log file handling
  launch/examples/launch_counters.py
  launch/launch/logging/__init__.py
  launch/launch/logging/handlers.py
  launch/test/launch/test_logging.py
Labels: in review

#235 Allow SomeSubstitutionsType in variable_name of LaunchConfiguration substitution
  launch/launch/substitutions/launch_configuration.py
Labels: bug, in review

#240 Stop randomizing ROS_DOMAIN_ID by default in launch tests
  launch_testing/launch_testing/launch_test.py
Labels: bug, in review

#241 Please flake8 on launch package.
  launch/launch/events/execution_complete.py
  launch/launch/events/matchers.py
Labels: in review

#236 Enable reuse of launch testing functionality
  launch_testing/launch_testing/asserts/assert_output.py
  launch_testing/launch_testing/launch_test.py
  launch_testing/launch_testing/test_runner.py
  launch_testing/test/launch_testing/test_io_handler_and_assertions.py
  launch_testing_ament_cmake/cmake/add_launch_test.cmake
Labels: in review

#234 Moved some common code to LaunchDescriptionSource
  launch/launch/launch_description_source.py
  launch/launch/launch_description_sources/python_launch_description_source.py
  launch/test/launch/test_launch_description_source.py
Labels: enhancement, in review

#243 add non-asserting waitFor method
  launch_testing/launch_testing/io_handler.py
Labels: enhancement, in review

#244 Convert retreived path to CMake path for use.
  launch_testing_ament_cmake/cmake/add_launch_test.cmake
Labels: in review

#239 [add_launch_test] Correct default python executable for windows debug
  launch_testing_ament_cmake/cmake/add_launch_test.cmake
Labels: in review

#249 Do not check declared arguments of IncludeLaunchDescription subentities
  launch/launch/launch_description.py
  launch/test/launch/actions/test_include_launch_description.py
  launch/test/launch/test_launch_description.py
Labels: bug, in review

#251 Use --isolated if no ROS_DOMAIN_ID is set to help parallel testing
  launch_testing/README.md
  launch_testing/launch_testing/domain_coordinator.py
  launch_testing/launch_testing/launch_test.py
Labels: enhancement
