Repository ros2/launch, pull requests merged in 2019-10, with the labels that each got.

#343 [backport dashing] install package marker and manifest
  launch/resource/launch
  launch/setup.py
Labels: needs review

#344 [backport dashing] install package manifest
  launch_testing/setup.py
Labels: needs review

#350 add missing test dependency
  launch_testing_ament_cmake/package.xml
Labels: bug, in review

#351 Fix a small typo in the launch_testing README.
  launch_testing/README.md
Labels: in review
