Repository ros2/launch, pull requests merged in 2019-07, with the labels that each got.

#270 Add parsing method for `DeclareLaunchArgument`
  launch/launch/actions/declare_launch_argument.py
  launch/launch/frontend/parser.py
  launch_xml/test/launch_xml/test_arg.py
Labels: enhancement, in review

#273 Add parsing method for dirname substitution
  launch/launch/frontend/expose.py
  launch/launch/frontend/parse_substitution.py
  launch/launch/substitutions/this_launch_file_dir.py
  launch/test/launch/frontend/test_substitutions.py
Labels: enhancement, in review

#265 [execute_process] emulate_tty configurable and defaults to true
  launch/examples/disable_emulate_tty_counters.py
  launch/launch/actions/execute_process.py
  launch/test/launch/actions/test_emulate_tty.py
Labels: enhancement

#274 fix linter warnings
  launch/launch/action.py
  launch/launch/actions/declare_launch_argument.py
  launch/launch/frontend/expose.py
  launch/launch/frontend/parser.py
Labels: in review

#271 Refactor `launch.frontend` file loading
  launch/launch/__init__.py
  launch/launch/frontend/__init__.py
  launch/launch/frontend/parser.py
  launch/launch/invalid_launch_file_error.py
  launch/launch/launch_description_sources/__init__.py
  launch/launch/launch_description_sources/any_launch_description_source.py
  launch/launch/launch_description_sources/any_launch_file_utilities.py
  launch/launch/launch_description_sources/frontend_launch_description_source.py
  launch/launch/launch_description_sources/frontend_launch_file_utilities.py
  launch/launch/launch_description_sources/python_launch_description_source.py
Labels: enhancement, in review

#277 Revert "Revert "[execute_process] emulate_tty configurable and defaults to true""
  launch/examples/disable_emulate_tty_counters.py
  launch/launch/actions/execute_process.py
  launch/test/launch/actions/test_emulate_tty.py
  launch/test/launch/actions/test_include_launch_description.py
  launch_testing/launch_testing/asserts/assert_output.py
  launch_testing/launch_testing/io_handler.py
  launch_testing/launch_testing/test_runner.py
  launch_testing/package.xml
  launch_testing/test/launch_testing/test_resolve_process.py
Labels: bug, in review

#281 Add parsing method to PythonExpression substitution
  launch/launch/substitutions/python_expression.py
  launch/test/launch/frontend/test_substitutions.py
Labels: enhancement, in review

#291 Add deprecated argument to LaunchDescription, add ThisLaunchFile substitution
  launch/launch/actions/include_launch_description.py
  launch/launch/frontend/parser.py
  launch/launch/launch_description.py
  launch/launch/substitutions/__init__.py
  launch/launch/substitutions/this_launch_file.py
  launch/test/launch/substitutions/test_this_launch_file.py
  launch/test/launch/test_launch_description.py
  launch_xml/test/launch_xml/test_deprecated_launch_file.py
Labels: enhancement, in review

#280 fix encoding handling when writing to stdout and log files
  launch/examples/launch_counters.py
  launch/launch/logging/__init__.py
  launch/test/launch/test_logging.py
Labels: bug, in review
