Repository ros2/launch, pull requests merged in 2019-03, with the labels that each got.

#192 Add normalize_parameters and evaluate_paramters
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/parameters_type.py
  launch_ros/launch_ros/utilities/__init__.py
  launch_ros/launch_ros/utilities/evaluate_parameters.py
  launch_ros/launch_ros/utilities/normalize_parameters.py
  test_launch_ros/test/test_launch_ros/actions/test_node.py
  test_launch_ros/test/test_launch_ros/test_normalize_parameters.py
Labels: in review

#191 Drop legacy launch package
  launch/launch/__init__.py
  launch/launch/legacy/__init__.py
  launch/launch/legacy/arguments.py
  launch/launch/legacy/exit_handler.py
  launch/launch/legacy/launch.py
  launch/launch/legacy/launcher.py
  launch/launch/legacy/loader.py
  launch/launch/legacy/main.py
  launch/launch/legacy/output_handler.py
  launch/launch/legacy/protocol.py
  launch/launch/legacy/task.py
  launch/setup.py
  launch/test/legacy/counter.py
  launch/test/legacy/launch_counter.py
  launch/test/legacy/launch_multiple_counters.py
  launch/test/legacy/test_interrupt_default_launcher.py
  launch/test/legacy/test_launch_args.py
  launch/test/legacy/test_launch_with_coroutine.py
  launch/test/legacy/test_multiple_launch.py
  launch/test/legacy/test_non_primary_return_code.py
  launch_testing/launch_testing/legacy/__init__.py
Labels: in review

#193 Plumb rclpy.init context to get_default_launch_description
  launch_ros/launch_ros/default_launch_description.py
  ros2launch/ros2launch/api/api.py
Labels: in review

#200 fix test_env_testing test
  launch_testing/test/test_env_passing.py
Labels: in review

#199 update logger.warn (deprecated) to logger.warning
  launch/launch/actions/execute_process.py
  launch/launch/launch_service.py
  launch_ros/launch_ros/actions/lifecycle_node.py
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/default_launch_description.py
Labels: in review

#198 Fix event loop closed bug
  launch/launch/actions/execute_process.py
Labels: in review

#178 Add test actions
  launch/launch/actions/execute_process.py
  launch_testing/CMakeLists.txt
  launch_testing/launch_testing/__init__.py
  launch_testing/launch_testing/actions/__init__.py
  launch_testing/launch_testing/actions/gtest.py
  launch_testing/launch_testing/actions/pytest.py
  launch_testing/launch_testing/actions/test.py
  launch_testing/launch_testing/output.py
  launch_testing/package.xml
  launch_testing/setup.py
  launch_testing/test/dummy_tests/dummy.cpp
  launch_testing/test/dummy_tests/dummy.py
  launch_testing/test/dummy_tests/locking.cpp
  launch_testing/test/dummy_tests/locking.py
  launch_testing/test/launch_testing/test_gtest.py
  launch_testing/test/launch_testing/test_pytest.py
Labels: in review

#145 Add LaunchLogger class
  launch/launch/__init__.py
  launch/launch/actions/declare_launch_argument.py
  launch/launch/actions/execute_process.py
  launch/launch/actions/log_info.py
  launch/launch/actions/timer_action.py
  launch/launch/launch_context.py
  launch/launch/launch_description_sources/python_launch_description_source.py
  launch/launch/launch_introspector.py
  launch/launch/launch_service.py
  launch/launch/logging.py
  launch/launch/utilities/signal_management.py
  launch/test/launch/test_logging.py
  launch_ros/launch_ros/actions/lifecycle_node.py
  launch_ros/launch_ros/actions/node.py
  launch_ros/launch_ros/default_launch_description.py
Labels: in review

#202 Replace characters with marker when there is a decoding error
  launch/launch/actions/execute_process.py
Labels: in progress

#201 Make 'ros2 launch' work again.
  launch_ros/examples/lifecycle_pub_sub_launch.py
  launch_ros/examples/pub_sub_launch.py
  ros2launch/ros2launch/api/api.py
Labels: in review

#212 fix treating stderr output separate from stdout
  launch/launch/actions/execute_process.py
Labels: bug, in review

#217 Log launch logging config before running.
  launch/launch/launch_service.py
  launch/launch/logging.py
Labels: in review

#218 Support external ExecuteProcess output overrides.
  launch/launch/actions/execute_process.py
Labels: in review

#219 one sentence per line in docs
  launch/launch/actions/execute_process.py
Labels: in review

#216 Add SetEnvironmentVariable and UnsetEnvironmentVariable actions #164
  launch/launch/actions/__init__.py
  launch/launch/actions/set_environment_variable.py
  launch/launch/actions/unset_environment_variable.py
  launch/test/launch/actions/test_set_and_unset_environment_variable.py
Labels: in progress

#223 Remove whitespace in keyword arg (#169)
  launch/launch/actions/execute_process.py
Labels: in review
