Repository ros2/launch, pull requests merged in 2020-03, with the labels that each got.

#384 Add support for anon substitution
  launch/launch/substitutions/__init__.py
  launch/launch/substitutions/anon_name.py
  launch/test/launch/substitutions/test_anon_name.py
Labels: enhancement

#393 [backport dashing] Fix import OnProcessStart from event_handlers
  launch/launch/event_handlers/__init__.py
Labels: bug, in review

#346 Warn that old-style ready_fn and test attributes will be deprecated
  launch_testing/launch_testing/loader.py
  launch_testing/test/launch_testing/examples/good_proc_launch_test.py
  launch_testing/test/launch_testing/test_proc_info_assertions.py
  launch_testing/test/launch_testing/test_resolve_process.py
  launch_testing/test/launch_testing/test_runner_results.py
  launch_testing/test/launch_testing/test_xml_output.py
Labels: enhancement, help wanted
